version: "1.0"

#Specify inspection profile for code analysis
profile:
  name: qodana.starter

projectJDK: "21" #(Applied in CI/CD pipeline)

failureConditions:
  severityThresholds:
    any: 15
    critical: 5
    testCoverageThresholds:
    fresh: 70
    total: 50

linter: jetbrains/qodana-jvm-community:2025.2
