# Dependabot configuration for project
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  # Gradle dependencies (Kotlin, libraries, etc.)
  -
    package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 10
    reviewers:
      - "rkociniewski"
    assignees:
      - "rkociniewski"
    labels:
      - "dependencies"
      - "gradle"
    commit-message:
      prefix: "build"
      prefix-development: "build"
      include: "scope"
    # Group related updates
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
          - "kotlin-*"
      testing:
        patterns:
          - "*junit*"
          - "*test*"
          -

          # GitHub Actions workflows
  -
    package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 5
    reviewers:
      - "rkociniewski"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "*"
